[changelog]
header = """# Changelog"""
body = """
{% if version %}\
    ## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}**:{% endif %} {{ commit.message | upper_first }}
    {% endfor %}
{% endfor %}
"""
trim = true


[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
tag_prefix = "v"
require_conventional = false

commit_parsers = [
    { message = "^Merge", skip = true },
    { message = "^*.\\(add.*\\)", group = "Added" },
    { message = "^*.\\(remove.*\\)", group = "Removed" },
    { message = "^fix", group = "Fixed" },
    { message = "^docs", group = "Changed" },
    { message = "^chore", group = "Changed" },
    { message = "^test", group = "Changed" },
    { message = "^style", group = "Changed" },
    { message = "^refactor", group = "Changed" },
    { message = "^ci", group = "Changed" },
    { message = "^build", group = "Changed" },
    { message = "^*.\\(deprecate.*\\)", group = "Deprecated" },
    { message = "^*.\\(security\\)", group = "Security" },

]
filter_commits = false
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false