// This is a dummy for version.hpp, since it is
// generated by meson at build time, this is here
// for development
#pragma once
#ifndef GOD_VERSION_HPP
#define GOD_VERSION_HPP

#define GOD_VERSION_MAJOR "0"
#define GOD_VERSION_MINOR "1"
#define GOD_VERSION_PATCH "0"

#define GOD_VERSION "0.1.0"

#endif