# SPDX-FileCopyrightText: 2025 Will Reed <wreed@disroot.org>
#
# SPDX-License-Identifier: LGPL-3.0-or-later

[book]
authors = ["Will Reed"]
language = "en"
src = "source"
title = "Libgod"

[output.html]
additional-css = [
    "theme/custom.css",
    "theme/admonish.css",
    "theme/syntax.css"
]
default-theme = "navy"
preferred-dark-theme = "navy"
preferred-light-theme = "rust"

[preprocessor]
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0"